services:
  - type: web
    name: punjabi-word-corrector
    env: python
    plan: free
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
